### ISSUE TITLE
Cannot import name format_hdp_stack_version

### ISSUE THREAD

**Issue by ildarmf** [abajwa-hw/ambari-flink-service#4]
Hello! I have problem when I install flink in Hortonworks. Help to solve the problem

`Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/FLINK/package/scripts/flink.py", line 164, in <module>
    Master().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 280, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/FLINK/package/scripts/flink.py", line 12, in install
    import params
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/FLINK/package/scripts/params.py", line 5, in <module>
    from resource_management.libraries.functions.version import format_hdp_stack_version
ImportError: cannot import name format_hdp_stack_version`

**Comment by ildarmf** [comment]
Apache Ambari Version 2.4.0.0 
Hadoop 2.5

**Comment by ildarmf** [comment]
solved https://github.com/ildarmf/hortonworks-flink.git

**Comment by abourakba** [comment]
Most of the people will consult the page and the repo is no more available.
According to this page  : https://github.com/Symantec/ambari-cassandra-service/issues/11
In params.py You should replace  format_hdp_stack_version  by format_stack_version 
Credits goes to @juan-echeverria
